import fs from "node:fs";

export function buildIconsTypings(dir: string) {
  console.log(__dirname);
  const icons = fs.readdirSync(dir, { recursive: true }) as string[];
  console.log(icons);
  const names = icons
    .filter((name) => name.endsWith(".svg"))
    .map((path) => path.split("/").pop()!.replace(".svg", ""));

  const file = `// This file is generated by buildIconsTypings function
// Do not edit it manually!

export const iconNames = [
${names.map((name) => `  "${name}"`).join(",\n")}
] as const;

export type IconName = typeof iconNames[number];
`;
  fs.writeFileSync(`${dir}/icons.ts`, file);
}
