import fs from "node:fs";

export function buildIconsTypings(dir: string) {
  console.log(__dirname);
  const icons = fs.readdirSync(dir);
  const names = icons.map((icon) => icon.split(".")[0]).filter(Boolean);

  const file = `// This file is generated by buildIconsTypings function
// Do not edit it manually!

export const iconNames = [
${names.map((name) => `  "${name}"`).join(",\n")}
] as const;

export type IconName = typeof iconNames[number];
`;
  fs.writeFileSync(`${dir}/icons.ts`, file);
}
